### ISSUE TITLE
Export to SQLite - Boolean values

### ISSUE THREAD

**Issue by paulator** [Wisser/Jailer#10]
Hi,
I have an error when exporting data to SQLite.

Discovered behavior: 
When I export from PostgreSQL -> SQLite, I get 'true' and 'false' as values for Boolean values.

Expected behavior: 
SQLite doesn't support boolean values. According to https://stackoverflow.com/questions/843780/store-boolean-value-in-sqlite the values should be stored as 0 and 1

Environment: 
SourceDB: PostgreSQL
TargetDB: SQLite
Jailer version: 8.2.1

**Comment by Wisser** [comment]
Hi,

[jailer.zip](https://github.com/Wisser/Jailer/files/2754251/jailer.zip)
I've created a patch for this issue (based on 8.2.5). Please replace the file "jailer.jar" in the attached zip and have a try.

**Comment by paulator** [comment]
Thank you for the fix. It works as expected!
