### ISSUE TITLE
Analyzing a Postgres DB with lots of partitioned tables creates seperate tables for each partition

### ISSUE THREAD

**Issue by KatamariJr** [Wisser/Jailer#109]
### Description of the Issue
Analyzing a Postgres DB with lots of partitioned tables creates separate tables for each partition, making it very hard to work with.

### Steps to Reproduce the Issue
1. Analyze a Postgres database with partitions

### Expected Behavior
Analyzing a database that contains tables which have multiple partitions would import a single logical table to work with in Jailer for subsetting. Possibly an analyzation setting to toggle this feature.

### Actual Behavior
![image](https://github.com/Wisser/Jailer/assets/4542759/8d82341f-473e-4fa1-93cc-b0a2b38d117e)
Importing a table with lots of partitions makes individual tables for every partition.

### Debug Information
Windows 10, Jailer 15.4, connecting to Postgres 14.9

**Comment by Wisser** [comment]
Do you use declarative partitioning or partitioning via inheritance?

https://www.postgresql.org/docs/current/ddl-partitioning.html

**Comment by Wisser** [comment]
I have found a solution for declarative partitioning. Only the partitioned table ("PARTITION BY")  is imported, not the partitions ("PARTITION OF").
You can find it here: https://sourceforge.net/projects/jailer/files/stage/

Please try this out.

**Comment by KatamariJr** [comment]
This works great! All the tables were found as a single table rather than their partitions. Thank you!
