### ISSUE TITLE
Postgres password authentication failing from CLI

### ISSUE THREAD

**Issue by phoolish-philomath** [Wisser/Jailer#11]
I'm having trouble connecting to a database for certain passwords when running Jailer from the command-line:
`Error: org.postgresql.util.PSQLException: FATAL: password authentication failed for user...`

I believe it is because of special characters in the password because a password like "pancakes" will work but a password like "qx#PA7xXu$Oo" will fail. However, when I connect with the GUI, it works for every password. I tried percent-encoding, so the second password would be passed like "qx%23PA7xXu%24Oo".

The command I am running is:

`sh jailer.sh build-model org.postgresql.Driver jdbc:postgresql://<host>:<port>/<database>?ssl <user> "<password>" -datamodel datamodel`
I have tried without ssl as well and same outcome.

I'm using the postgresql-42.2.0.jre7.jar driver.

**Comment by Wisser** [comment]
Single quote the password, to not let the shell interpret special characters.
Tip: use "echo" to test whether the command-line arguments are taken literally:
```
$ echo '<password>'
<password>

```

**Comment by phoolish-philomath** [comment]
Thank you! This worked perfectly.
