### ISSUE TITLE
The route for the custom installation is absent.

### ISSUE THREAD

**Issue by GouthamGuna** [Wisser/Jailer#115]
### Is your feature request related to a problem? Please describe.
The custom installation path is not specified.

### Describe the solution you'd like
During the installation of an application, it may request better permissions or resources.

@Wisser, thank you for this wonderful tool.

**Comment by Wisser** [comment]
Unfortunately, the installation files generated by jlink do not allow the user to influence the installation.
However, you can just install the Java VM yourself and then place Jailer on the computer as you wish, as described here: 
https://wisser.github.io/Jailer/installation-2.htm
