### ISSUE TITLE
Saving the model files should be sorted

### ISSUE THREAD

**Issue by liebsche** [Wisser/Jailer#116]
The blocks in model files should be sorted alphabetically to make it easier to compare changes with a diff tool.

Please save the lines in the .jm files sorted within each block.

Specifically, it is about the blocks:

- `# association; ; restriction-condition`
- `#! block xml-mapping`
- `# known association; decision pending`

**Comment by Wisser** [comment]
This has been implemented in release 16.4.

**Comment by liebsche** [comment]
Great - thanx a lot!
