### ISSUE TITLE
Missing parantheses causes problems with HSTOREs containing newlines

### ISSUE THREAD

**Issue by saurabhnanda** [Wisser/Jailer#117]
In PostgreSQL, if an HSTORE column contains a newline, Jailer will export the value as...

```sql
'"key"=>"value' || chr(10) || 'with newlines"' :: hstore
```

... which results in the following error when executing in `psql`:

```
psql=# select '"key"=>"value' || chr(10) || 'with newlines"' :: hstore;
ERROR:  Syntax error near "n" at position 5
LINE 1: select '"key"=>"value' || chr(10) || 'with newlines"' :: hst...
```

However, if the HSTORE value were to be exported with parantheses, as shown below...

```sql
('"key"=>"value' || chr(10) || 'with newlines"') :: hstore
```

...I believe it would work:

```
psql=# select ('"key"=>"value' || chr(10) || 'with newlines"') :: hstore;
     hstore     
----------------
 "key"=>"value +
 with newlines"
(1 row)
```

**Comment by Wisser** [comment]
Thank you for the error report!
This has been fixed in release 16.4.

**Comment by saurabhnanda** [comment]
@Wisser thank you for the quick response. Actually, I discovered this to be a bug for `TEXT` columns as well. Does 16.4 fix that as well?

**Comment by Wisser** [comment]
Yes, it works for all literals. Let me know if you find any other issues.

**Comment by saurabhnanda** [comment]
@Wisser I've come back to this issue to remove the HACK that I had put in my export model. Unfortunately, in the `16.4` UI, I cannot find where to remove the following from:

```
#! block filter templates
T;hstore fix;remove_newlines_from_hstore_value(${old-value});enabled;Export;;
C;TYPE;EQUALS;hstore;
``

**Comment by Wisser** [comment]
Did the fix work for you?

The entry in the model file is a “filter template”. These can be edited or deleted in the “Filter editor” (“Edit” -> “Filter editor”).
See screenshots.

![image](https://github.com/user-attachments/assets/e1a66fef-b613-493f-adac-ed1e877e306b)
![image](https://github.com/user-attachments/assets/d4b23d35-9650-449b-a4bf-7a034e46b6bc)
