### ISSUE TITLE
Copy-Paste not working on mac

### ISSUE THREAD

**Issue by franz-see** [Wisser/Jailer#12]
Hi, 

I am using jailer_8.5.5 

```
$ java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```

```
macOS Mojave
Version: 10.14.3
```

Im running with ./jailerGUI.sh

Copy paste does not work. I've tried with Cmd+V and Right-Clicking then pasting, both does not work. Also, the right-click context menu does not show up as well.

**Comment by Wisser** [comment]
Hi,

with the native look and feel that should behave as expected. To activate please it, use the menu item "Settings"->"Native Look&Feel".

**Comment by franz-see** [comment]
Nice! That works! thanks! :)
