### ISSUE TITLE
Multiple table selection

### ISSUE THREAD

**Issue by cxplonka** [Wisser/Jailer#13]
It would be nice if i could select multiple rows (STRG + click) in the data browser and then click "select row(s)" to select only this rows in the table.

**Comment by Wisser** [comment]
Hi,

yes, that would be a good feature. Thanks for the suggestion. I'm trying to implement that for the next release.

**Comment by cxplonka** [comment]
Thanks for the great work.

**Comment by Wisser** [comment]
Thank you.
Please note that the release 8.8.5 (which incorrectly calls itself 8.8.4.4) still has some problems in the data model selection dialog, which will hopefully be fixed soon.

**Comment by cxplonka** [comment]
Ok, thanks for the hint. But no problem, because the jailer workflow now gets more easier. 
P.S. I never want again access RDBMS systems anymore without jailer.. 🥇

**Comment by Wisser** [comment]
The problems in the data model selection dialog have been fixed in release 8.8.6.
