### ISSUE TITLE
JailerDataBrowser.sh::Error: Could not find or load main class net.sf.jailer.ui.databrowser.DataBrowser 

### ISSUE THREAD

**Issue by quickdraw6906** [Wisser/Jailer#17]
MacBook-Pro-8:Jailer sean$ ./JailerDataBrowser.sh
:/Users/sean/Library/Preferences/DataGrip2018.2/jdbc-drivers/PostgreSQL/42.2.5:config:lib/junit.jar:lib/commons-logging.jar:lib/log4j.jar:lib/args4j.jar:lib/spring.jar:lib/prefuse.jar:lib/sdoc-0.5.0-beta.jar:lib/activation-1.0.2.jar:lib/jaxb-core-2.3.0-b170127.1453.jar:lib/jaxb-impl-2.3.0-b170127.1453.jar:lib/jaxb-api-2.3.0-b170201.1204.jar:lib/jsqlparser-1.3.jar:lib/tablefilter-swing-5.3.1.jar:jailer.jar
Error: Could not find or load main class net.sf.jailer.ui.databrowser.DataBrowser
Caused by: java.lang.ClassNotFoundException: net.sf.jailer.ui.databrowser.DataBrowser

**Comment by quickdraw6906** [comment]
Issue is the repo on github lacks the jailer.jar file. I downloaded 9.1 at SourceForge and it worked.

**Comment by Wisser** [comment]
The repo does not contain this file because it is an artifact that is created by the build process. If you want to build the tool yourself, you need the "ant" build tool besides the JDK (https://ant.apache.org )

**Comment by Wisser** [comment]
I've thought about it and now I think it's better to check in the file as well. (Whatever I did now)
This way, the repository content is always usable without the need for a 3rd party tool.
Thanks for the thought push.

**Comment by quickdraw6906** [comment]
Some note about build instructions in README.md would be helpful.
