### ISSUE TITLE
[New feature] direct data deletion

### ISSUE THREAD

**Issue by jcaillon** [Wisser/Jailer#19]
Hello,

### Is your feature request related to a problem? Please describe.

The use case is the following; I have a database with a consequential amount of data (~12Go) that I wish to trim down to a few Mo. For this, I build a WHERE predicate that target all the data I don't want to keep.

I want to delete the data using jailer. But for this, the only solution is to generate the .sql file that I will then need to execute to actually delete anything.

The problem is that this 2 step process is slow and moreover, the .sql file generated is too big.

### Describe the solution you'd like

What I wish I could do is use the **delete** command with the option `INTRA_DATABASE`. We can do this with the **export** command to directly copy data from a schema to another and generate a receipt file instead of the export .sql.

The command would look like:

```bash
jailer.bat delete database\extractionmodels\equipement.jm com.ibm.db2.jcc.DB2Driver jdbc:db2://localhost:50000/OMEGA db2admin adminDb2 -datamodel database\datamodel -d receipt.txt -threads 4 -entities 50 -format INTRA_DATABASE -source-schemamapping REFSCHEMA=REFSCHEMA -schemamapping REFSCHEMA=REFSCHEMA -scope LOCAL_DATABASE -check-primary-keys
```

### Describe alternatives you've considered

Generate the delete .sql and then execute it.

### Additional context

N/A

Best regards

**Comment by sebastian-jansson** [comment]
A workaround to this (That I'm using myself) is to write a script that calls jailer from the command line, and then executes the exported delete script using a CLI that fits your DBMS.
 (SQLcl works great for Oracle for e.,g).
