### ISSUE TITLE
How to use a different schema for working tables from UI??

### ISSUE THREAD

**Issue by aishydevil12286** [Wisser/Jailer#2]
Thanks for the awesome tool Ralph. I had a query about How to use a different schema for the working tables. I see no such option on the UI. Can you please help

**Comment by Wisser** [comment]
Hi, this repository is currently not up to date.
The lastest release 5.5.7 is available at https://sourceforge.net/projects/jailer
it allows you to specify a different schema for the working tables within the "Data export"-dialog.

**Comment by aishydevil12286** [comment]
Thanks for the prompt response Ralph. One more query.  I want to extract all the possible paths between two tables. Is there a way to do it. I found the static method findAssociation in Jailer.java that finds the shortest association path, but there is no method for all paths. But, when I click on a table in the closure view then it is able to show all the paths between the two tables. So, definitely there is some method used behind the scenes. Can you point me in that direction please. I need this info ASAP.
