### ISSUE TITLE
Schemamapping incorrectly used for deletion script

### ISSUE THREAD

**Issue by jcaillon** [Wisser/Jailer#21]
### Description of the Issue

The option -schemamapping is not used for all the statements generated during the generation of a delete script.

### Steps to Reproduce the Issue

I execute this command on my database:

```bash
"C:\Program Files\Java\jre1.8.0_221\bin\java.exe" net.sf.jailer.Jailer delete C:\data\omega\repo\Omega\omega\database\extractionmodels\equipement.jm com.ibm.db2.jcc.DB2Driver jdbc:db2://localhost:50000/OMEGA *** *** -datamodel C:\data\omega\repo\Omega\omega\database\datamodel -d C:\Users\jcaillon\Desktop\test_delete.sql -threads 4 -entities 50 -format SQL -source-schemamapping REFSCHEMA=BUG44762 -schemamapping REFSCHEMA=REFSCHEMA -scope LOCAL_DATABASE -where "T.IDEQUIPEMENT IN (44762) " -check-primary-keys
```

### Expected Behavior

This should generate a .sql script which deletes rows that are not used aside from the exported rows. The .sql script should target the `REFSCHEMA` (which is the set to be the *target* schema).

### Actual Behavior

In the generated scripts, I have some statements targeting `REFSCHEMA` and other statements targeting `BUG44762` (which is my **source** schema).

SQL sample:

```sql
Delete from BUG44762.ADRESSE Where IDADRESSE in (112324);
Delete from BUG44762.EXERCICECONTRAT Where IDEXERCICECONTRAT in (443);
Delete from BUG44762.FONCTIONTIERS Where IDFONCTIONTIERS in (13938);
Delete from BUG44762.INTERFACECOMPTABLE Where IDINTERFACECOMPTABLE in (36);
-- sync
Delete from BUG44762.LOTINTERFACE Where IDLOTINTERFACE in (49);
Delete from BUG44762.ADRESSE Where IDADRESSE in (16834);
-- sync
-- sync
-- explicit due to circular dependency
Update REFSCHEMA.UTILISATEUR set IDMAJUTI=null, IDORGANISME=null, IDPARTENAIRE=null Where IDUTILISATEUR=48192;
-- explicit due to circular dependency
Update REFSCHEMA.CONTRAT set IDMAJUTI=null, IDPERIODEGESTION=null, IDDOSSIERAFC=null, IDUTILISATEUR=null, IDCONTRATCONVENTIONPARENT=null Where IDCONTRAT=73043;
-- explicit due to circular dependency
```

The script will not work and it will modify my source schema instead of my target schema.

### Debug Information

Using jailer 8.8.6.

Best regards,

**Comment by Wisser** [comment]
I think it's the "`Update`" statements that refer to the wrong schema. The deletion scripts are actually used to **delete in the source schema**?!

What do you think?

**Comment by jcaillon** [comment]
Oh. Well, now that you mention it, it makes sense yes. 

In my mind, both the delete/export were reading the **source schema** to generate the needed statements and the **target schema** was used to now which schema name should be in the final script. However, for the deletion script, it makes sense to not use the target schema name (in most case we would set the target schema equals to the source schema).

**Comment by Wisser** [comment]
In release 9.1.5 there is a new cli-argument "-deletion-schemamapping" for the specification, from which schema rows are deleted. In the "Export" dialog, this mapping can be edited.
 
This way, rows can also be deleted from a schema different from the source schema.
 
If this argument is missing, the "-source-schemamapping" mapping is also used for deletion. Therefore, there is no behavior change for existing scripts.

**Comment by jcaillon** [comment]
Sounds terrific thx :)

I will try it this instant

**Comment by jcaillon** [comment]
I can confirm that it works as expected, thank you again :)
