### ISSUE TITLE
Jailer doesn't handle SQLite fields with space in field name

### ISSUE THREAD

**Issue by audiomuze** [Wisser/Jailer#22]
### Description of the Issue
Jailer doesn't handle SQLite fields/columns with space in field name correctly

### Steps to Reproduce the Issue
Try loading any table with a field name containing a space e.g. "recording location"

### Expected Behavior
Fields containing on or more spaces in field name should be handled like any other.

### Actual Behavior
Throws an error

### Debug Information
Arch Linux, Jailer 9.1.7.2
![Screenshot from 2019-11-16 14-53-36](https://user-images.githubusercontent.com/6852511/68995040-564e5900-0881-11ea-856f-d7b80f3a6642.png)

**Comment by Wisser** [comment]
Fixed in master.
I also updated the SQLite JDBC driver to version 3.28.

**Comment by audiomuze** [comment]
Thanks, will test today.

**Comment by Wisser** [comment]
Fixed in release 9.2.1.
