### ISSUE TITLE
Publish Jailer jar files to maven central repo

### ISSUE THREAD

**Issue by vsgfe** [Wisser/Jailer#23]
### Is your feature request related to a problem? Please describe.
We are using the jailer-engine embedded in our tool chain. To integrate new Jailer versions we have to manually upload the jailer-engine jar to our local repository. This manual process is somewhat cumbersome and error prone.

### Describe the solution you'd like
It would be nice if jailer-engine-jar was published to the maven central repository(https://maven.apache.org/repository/).
Then our build process would just fetch the versions from there.
The dependencies (args4j, com.h2database:h2, log4j) should be stated in the pom.xml so that dependencies can be fetched transitive.

### Describe alternatives you've considered
Manually uploading the jars to our local repository.

**Comment by Wisser** [comment]
Jailer-engine is published in maven central.
https://mvnrepository.com/artifact/io.github.wisser/jailer-engine

**Comment by vsgfe** [comment]
Thank you very much!
