### ISSUE TITLE
MSSQL: Request - Option to enable square brackets for column identifiers instead of double quotes

### ISSUE THREAD

**Issue by jamespdaily** [Wisser/Jailer#26]
Would love to see an option that would create MSSQL scripts that qualify column names with square brackets instead of double quotes, as show in the examples below.

`Insert into Daybreak.UserAgreementHistories([Timestamp]) values `

instead of

`Insert into Daybreak.UserAgreementHistories("Timestamp") values `

**Comment by Wisser** [comment]
Hi,
what would be the benefit of using square brackets instead of double quotes?
