### ISSUE TITLE
Syntax error creating tables in PostgreSQL

### ISSUE THREAD

**Issue by urban-dnowak** [Wisser/Jailer#27]
Hi Ralf,

using version 9.3 of Jailer creating of a table results in a syntax error.

> net.sf.jailer.database.SqlException: "ERROR: syntax error at or near "CREATE"
>   Position: 103" in statement "CREATE TABLE jailer.JAILER_IFM ( OLD_VALUE1 int8, NEW_VALUE1 int8, OLD_VALUE2 int8, NEW_VALUE2 int8 ) CREATE UNLOGGED TABLE"
> 	at net.sf.jailer.database.Session.execute(Session.java:967)
> 	at net.sf.jailer.util.SqlScriptExecutor$3.run(SqlScriptExecutor.java:371)
> 	at net.sf.jailer.util.SqlScriptExecutor.execute(SqlScriptExecutor.java:453)
> 	at net.sf.jailer.util.SqlScriptExecutor.executeScript(SqlScriptExecutor.java:346)
> 	at net.sf.jailer.util.SqlScriptExecutor.executeScript(SqlScriptExecutor.java:129)
> 	at net.sf.jailer.api.Importer.execute(Importer.java:57)
>  	[...]

According to [PostgreSQL documentation](https://www.postgresql.org/docs/current/sql-createtable.html) the UNLOGGED parameter should be placed in prefix.

**Comment by Wisser** [comment]
Thank you for the report.

**Comment by urban-dnowak** [comment]
That solved my problem. 
Thanks for your fast response.
