### ISSUE TITLE
[New feature] Add fake data to anonymise the extracted data

### ISSUE THREAD

**Issue by cedricms** [Wisser/Jailer#29]
### Is your feature request related to a problem? Please describe.
The FAQ (http://jailer.sourceforge.net/faq.html) suggests using SQL functions and test tables to anonymise data; in addition to this, it would be great to be able to call certain key words to generate fake data. This would avoid having database tables who are not business related.

### Describe the solution you'd like
"Java Faker" (https://github.com/DiUS/java-faker) offers plenty of "fake data" options that would be useful for data anonymisation.

As "${old-value}" is available in the filter editor, I had in mind the ability to call on "${faker.name().fullName()}" or "${faker.address().streetAddress()} in order to keep it as generic as possible.

If you approve this issue, I can look into implementing it.

**Comment by Wisser** [comment]
Thanks for the suggestion. I'm gonna go take a closer look at "Java Faker".
But maybe we should implement a more general concept, so that filters can also be evaluated on the client side (instead of only on the DBMS side as at present).

Unfortunately, I have little time at the moment.
