### ISSUE TITLE
Preserve schema names in PostgreSQL export

### ISSUE THREAD

**Issue by markovendelin** [Wisser/Jailer#35]
### Is your feature request related to a problem? Please describe.

When using PostgreSQL, we have database with the several related schemas, in context of PostgreSQL. In this respect, table name is `test.table` with `test` denoting schema. 

### Describe the solution you'd like

* If I export the data to another PostgreSQL database, I would like to have an option for preserving the same partitioning of the tables into schemas. 
* For databases without such schema support, would be great to have an option for formatting the end table name. For example, `test.table` -> `test_table`.

**Comment by Wisser** [comment]
It is quite possible that a data model contains several schemas. For this purpose the schemas have to be analyzed one after the other in the context of the same data model. In the "Analyze Database" dialog the schema can be entered explicitly.

**Comment by markovendelin** [comment]
I should have checked as it looked as if database table name was not preserved while exporting. In reality, it is and I am getting `test.table` back. Sorry for noise, closing the issue as it is implemented for me already.
