### ISSUE TITLE
Publish Jailer to the AUR reositories or provide instuctions on how to install on arch linux 

### ISSUE THREAD

**Issue by cocoonkid** [Wisser/Jailer#39]
Please Publish Jailer to the AUR repositories or provide instuctions on how to install on arch linux 

Thank you very much.

**Comment by Wisser** [comment]
I am not familiar with that. What would I have to do?

**Comment by cocoonkid** [comment]
https://wiki.archlinux.org/index.php/AUR_submission_guidelines

**Comment by AlphaJack** [comment]
I've just packaged it starting from the .deb file, so no effort is required on @Wisser part: https://aur.archlinux.org/packages/jailer/

**Comment by Wisser** [comment]
Thank you very much.
