### ISSUE TITLE
(Minor) Dropdown menu disabling inconsistency

### ISSUE THREAD

**Issue by sebastian-jansson** [Wisser/Jailer#40]
### Description of the Issue
When opening the export window from within the Extraction model editor, if you had "**Local database**" set as your "**Working table scope**" in your last export, the dropdown menu for "**Working table Schema**" will be enabled again.
To disable it again, you have to cycle the "Working table scope" setting back to "**local database**".

### Expected Behavior
That the dropdown menu for "Working table schema" stays disabled when the table scope is still set to "local database" after the last export.

### Debug Information
Windows 10 1909
Jailer 10.3.5

**Comment by Wisser** [comment]
Thanks for the report.

**Comment by sebastian-jansson** [comment]
Thanks for the quick fix and reply Wisser!
