### ISSUE TITLE
Parameters not working when using complex filters

### ISSUE THREAD

**Issue by sebastian-jansson** [Wisser/Jailer#41]
### Description of the Issue
When adding parameters to certain filter expressions (Whether that's through templates or direct ones), the parameter gets blank space characters added to it, rendering it useless as jailer won't recognize it as a parameter anymore , with a failed export as the result.
![image](https://user-images.githubusercontent.com/54795430/111519234-2950d580-8757-11eb-8115-5eb71235f537.png)

I noticed that this bug is only visible when opening the expression editor (Apart from the error log output), viewing it "inline" or directly displays the parameter correctly:

![image](https://user-images.githubusercontent.com/54795430/111517740-b09d4980-8755-11eb-867d-b387f01a404d.png)

I attempted many different combinations, (My real filter expressions has lots of concatenation operators), but even simple ones as the example above fails. The only expressions I could get consistent _working_ results with are ones where the full expression is solely the parameter name itself.

Other things that did not help:
- Adding the parameter from the sidebar instead of typing it out.
- Only using the parameter once instead of twice as in my full expression.
- Different naming standards did not resolve the issue. In fact, it happens for the default "old-value" parameter as well.

### Expected Behavior
At save, runtime & edit, one expects the parameter to stay the way it was written out when closing the editor.

### Actual Behavior
Parameters are changed into: **$ { to_plc_id }** from: **${to_plc_id}**.

### Debug Information
Windows 10 1909
Jailer 10.3.5

**Comment by sebastian-jansson** [comment]
Forgot to add, when replacing the parameter in the filter expression with the actual value I'm assigning the parameter results in a successful export.

**Comment by Wisser** [comment]
Thanks for the report. I will have a look at it as soon as possible.

**Comment by sebastian-jansson** [comment]
> Thanks for the report. I will have a look at it as soon as possible.

Many thanks Wisser!

**Comment by Wisser** [comment]
The reason for this was that the SQL formatter unfortunately inserted spaces in awkward places.
I have corrected this and published the fix in release 10.4.

**Comment by sebastian-jansson** [comment]
That was quick! Thanks a bunch., I'll download 10.4 and give it a try :) 

I'm already loving this tool, has saved me a bunch of time for moving data around.
