### ISSUE TITLE
Cycle breaking? Is it present?

### ISSUE THREAD

**Issue by raresboza** [Wisser/Jailer#50]
I saw the patch notes on the Jailer site stating that since the 4th of February one can submit a database containing circular references at it will break them. I was very curious as to how this would work, however upon a closer inspection of the code, I could only find the removal of reflexive cycles. Am I missing something?

P.S: Sorry for posting this in an issue tab, but I could not find a better way to contact the devs.

**Comment by Wisser** [comment]
Presumably you mean this statement:

"Cycles in parent-child relationships will be detected and broken. Thus, such data can be exported by deferring the insertion of nullable foreign keys."

In general, data is exported in an order that does not violate foreign key constraints during import. That means: parents are placed before their children.
This obviously does not work if there is a cycle in this respect. These cases are recognized and handled by first setting the foreign key columns to "null" (if they are nullable) in the "insert" statements of the export script, and then setting them to the then existing primary keys with subsequent "update" statements.
