### ISSUE TITLE
Button to toggle Link on Hover/Link on Select for Details Panel

### ISSUE THREAD

**Issue by cdxf** [Wisser/Jailer#66]
### Is your feature request related to a problem? Please describe.

For now, the details panel will update the value on hover. I want to have a options to toggle between link on hover and link on select (so I can inspect the value)
![image](https://user-images.githubusercontent.com/6419729/138445377-65cc9af3-0648-4a27-b44e-2f81991bd919.png)

### Describe the solution you'd like
![image](https://user-images.githubusercontent.com/6419729/138445624-bf2b5a75-fe18-43bd-84e7-27191cf9babe.png)
Add a button at the top of detail pannel to toggle Link on Hover/Link on Select.
### Describe alternatives you've considered

Double click on the row to show details popup which is not convenient.

### Additional context

- Be able to select/copy cell value on the details panel also.
- Change double link behavior from Show Details to Select Cell Value
- Use Details Panel as a replacement for details popup

**Comment by Wisser** [comment]
Implemented in 11.2.5
