### ISSUE TITLE
Lack of navigation arrows

### ISSUE THREAD

**Issue by grykar** [Wisser/Jailer#74]
Lack of navigation arrows. They have been seen last time in version 10.6 - they are very useful.

![obraz](https://user-images.githubusercontent.com/47362723/145600989-b92d42a8-352a-4b7f-b400-b4bbf5586842.png)
![obraz](https://user-images.githubusercontent.com/47362723/145601038-29285ef0-682c-4516-82d0-0d23d72ed764.png)

**Comment by Wisser** [comment]
The arrows are back in release 11.2.7. Thanks for the hint!

**Comment by naxels** [comment]
I can confirm that on macOS 12.2 for Jailer 12.2 the arrows are back, issue can be closed.
