### ISSUE TITLE
Which files or folders should be included in VCS?

### ISSUE THREAD

**Issue by csonuryilmaz** [Wisser/Jailer#77]
Hi, first of all thanks to team for this great product. :pray:

I'm planning to keep `.jailer` in VCS (example, **git**) for tracking changes.

At first look, extraction model and data model seems to be important and valuable for us.

- Which files or folders should be included in VCS from `.jailer` and shareable between database developers?
- Which files or folders should be defined in `.gitignore`? (_mostly reproducible, locally generated and non-shareable ones_)

I've read documentation and searched in forum/github issues but couldn't find a clear answer yet. :thinking:

**Comment by Wisser** [comment]
Hi,
I would not keep the ".jailer" folder itself in a repository.
The data models and extraction models are the only artifacts that should be kept there. You can configure in which folder the data models are stored. (the "Base Folder", see screenshot below).
Each user can define the Base Folder in his workspace on his own. Similarly, the extraction models can be stored in the workspace itself. The tool remembers the last used folder for these models for each user.

![grafik](https://user-images.githubusercontent.com/861721/149122322-1983d867-a998-49b2-8269-35946764c283.png)

**Comment by csonuryilmaz** [comment]
:+1: Thanks. May I add `modelname.csv` to .gitignore?

As far as I see, when I modify data model with "UI > model > data model editor" (_for example, delete an unnecessary table from data model_), Jailer updates **last modification** column at `modelname.csv`.

I think it will cause git conflicts often, on data model changes for different developers.

When I delete it and make another change to data model Jailer creates the file itself. :heavy_check_mark: 

I didn't see any side-effect up-to-now but I'm also suspicious about other effects that I don't see yet.

**Comment by Wisser** [comment]
Yes, that's right. This file is purely informative for the indication of the last modification date and can be (git)ignored without any problems.
