### ISSUE TITLE
How to ignore (exclude) some tables from analyse database?

### ISSUE THREAD

**Issue by csonuryilmaz** [Wisser/Jailer#78]
Hi, let's assume I've created a data model at time `t0`. While working on data model, I also excluded some tables (_with "delete" button_) that are not important to export. (_like log tables or some temporary tables left from other people's workings_)

This database is continuously being updated by other teams. (_schema changes like add table, alter column ..._) So I have to check changes from time to time and update my data model continuous database subsetting.

I'm using "UI > model > analyse database" to get database updates at a later time `t1`.

Now, Jailer shows new tables and associations but I also see previously excluded tables as new tables. 

![2022-01-12_14-23](https://user-images.githubusercontent.com/7355362/149133616-2c83cbd6-5308-4b1e-a882-ab87ebd5c14a.png)

When I hit "ok" button, those tables  are added to data model. Or I have to remove them again from data model before "ok" button.

- Is there an easy way to define some tables as "excluded" or "ignored" from analyse database?
- Or is there another better workflow for this use case? (_Maybe I'm in the wrong way._)

**Comment by Wisser** [comment]
This is currently not possible. All tables of a schema to be analyzed are always taken over into the data model. There they would have to be removed manually if you do not want them in the data model.

Would an "exclude/ignore" feature make sense?
My thoughts on the subject were:
- If an unwanted table is associated with a wanted one, there could be inconsistencies in the result of the export/delete (if e.g. Parents are not wanted).
- If there are no such associations, the unwanted tables are isolated from the others and therefore should not interfere further.

What do you think?

**Comment by csonuryilmaz** [comment]
:+1: That makes sense. I think extraction model will be a better place to exclude unwanted relations.

In order to track future database changes continuously, I won't delete or remove any table manually from data model. (_Indeed some of them, especially trash ones, should be removed from database. So that, on next analyse database they will be removed from data model also._)

I will ignore (or exclude) all unwanted tables on extraction model. Since extraction model keeps tracking of excludes (_restrictions_), all unwanted relations won't be affected from future data model updates.
