### ISSUE TITLE
Test Connection: Socket timeout when connecting to remote PostgreSQL database hosted on AWS

### ISSUE THREAD

**Issue by Nezteb** [Wisser/Jailer#89]
### Description of the Issue

I am able to connect to this same database with both TablePlus and DBeaver, but not Jailer for some reason. I've triple verified the correct JDBC url format, host, username, and password.

This probably isn't specific to AWS; I'm guessing I'd have the same issue with any cloud provider. It's worth noting that I am on a company VPN in order to access the database, but again TablePlus and DBeaver handle that just fine (and I assume it's not an issue with Jailer and VPNs specifically).

<img width="804" alt="Screen Shot 2022-04-28 at 2 02 18 PM" src="https://user-images.githubusercontent.com/3588798/165827585-b8ce5f23-fec9-49e2-8afc-fe6e663ba632.png">

### Steps to Reproduce the Issue

Add a remote database connection pointing to an AWS-hosted Postgres instance and try to test the connection.

### Expected Behavior

I'd expect Jailer to be able to connect to databases like TablePlus and DBeaver.

### Actual Behavior

It doesn't seem to work no matter what I try; I always get the same socket timeout exception.

### Debug Information

Jailer version: 12.3
Driver: `lib/postgresql-42.2.16.jar`

**Comment by Wisser** [comment]
Maybe the driver is not compatible with the DBMS? Do you also use postgresql-42.2.16.jar for TablePlus and DBeaver?

**Comment by Wisser** [comment]
It could also be that you can only access the VPN via the system proxy. To use this, modify the file "jailerGUI.sh", line 34 to:

java -Xmx1200M **-Djava.net.useSystemProxies=true** -Djava.util.Arrays.useLegacyMergeSort=true -cp $CP net.sf.jailer.ui.ExtractionModelFrame "$@"

**Comment by Nezteb** [comment]
I'm an idiot and had a tiny typo (a lowercase "L" instead of an uppercase "i"), so disregard this entire issue. 🤦‍♂️
