### ISSUE TITLE
PSQLException: SSL error: Received fatal alert: handshake_failure

### ISSUE THREAD

**Issue by guettli** [Wisser/Jailer#99]
### Description of the Issue

I want to connect to my PG database running on localhost.

I get:

> PSQLException: SSL error: Received fatal alert: handshake_failure

Connection string:

> jdbc:postgresql://localhost:5432/mydb

I guess that Jailer wants to connect to an encrypted socket, but mine is not encrypted.

I use: jailer-database-tools_12.8-x64.deb

**Comment by Wisser** [comment]
If your PG server doesn't use SSL, you could try;
`jdbc:postgresql://localhost:5432/mydb?sslmode=disable `

**Comment by guettli** [comment]
Thank you

**Comment by johanleroux** [comment]
I'm trying to connect to a server that requires an SSL connection and getting the same error as above

`PSQLException: SSL error: Received fatal alert: handshake_failure`

Changing the `sslmode` without any success, the `ca.crt` for the database is installed on my system and connecting via the CLI `psql` works as expected even with `sslmode=verify-full` 

How would you specify a `ca.crt` in Jailer or even ignore the certificate completely?

**Comment by Wisser** [comment]
I am not very familiar with Postgresql.
Maybe this will help you: https://stackoverflow.com/questions/57969175/postgres-jdbc-connection-string-with-ssl-certficate-without-keystore
